### ISSUE TITLE
Uncaught TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by acidblue** [jaya1992/open-php-in-browser#1]
[Enter steps to reproduce:]

1. ...Clicked 'open php in browser' in the right click menu.
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 7 Professional 
**Thrown From**: [open-php-in-browser](https://github.com/jaya1992/open-php-in-browser) package 0.2.0

### Stack Trace

Uncaught TypeError: Cannot read property 'replace' of undefined

```
At C:\Users\rocko\.atom\packages\open-php-in-browser\lib\open-php-in-browser.coffee:20

TypeError: Cannot read property 'replace' of undefined
    at Object.processFile (/packages/open-php-in-browser/lib/open-php-in-browser.coffee:20:26)
    at /packages/open-php-in-browser/lib/open-php-in-browser.coffee:8:74)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/app.asar/src/atom-environment.js:1185:28)
    at EventEmitter.outerCallback (/app.asar/src/application-delegate.js:325:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -6:27.2.0 editor:newline (input.hidden-input)
     -6:23.2.0 core:backspace (input.hidden-input)
     -6:18.9.0 editor:newline (input.hidden-input)
  2x -6:00.4.0 core:move-right (input.hidden-input)
  2x -5:57.3.0 editor:newline (input.hidden-input)
     -5:10.7.0 core:backspace (input.hidden-input)
 28x -5:03.8.0 core:move-left (input.hidden-input)
     -4:56.5.0 core:move-down (input.hidden-input)
  2x -4:54.3.0 editor:newline (input.hidden-input)
     -3:24.4.0 php-server:start-document (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:38.3.0 open-php-in-browser:run (div.line.cursor-line)
```

### Non-Core Packages

```
atom-autocomplete-php 0.22.2 
open-php-in-browser 0.2.0 
php-analyser 0.2.0 
php-server 0.7.0 
```

**Comment by jaya1992** [comment]
Sorry, I'm hardly good at CoffeeScript. In my Mac OS, it works well.
